import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { draftMode } from 'next/headers'

import { DraftModeScript } from '@makeswift/runtime/next/server'

import '@/lib/makeswift/components'
import { MakeswiftProvider } from '@/lib/makeswift/provider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <DraftModeScript />
      </head>
      <body className={inter.className}>
        <header>
          <div className='flex justify-between items-center p-4 bg-gray-800 text-white'>
            <a href='/' className='text-xl font-bold'>Create Next App</a>
            <nav className='space-x-4'>
              <a href='/'>Home</a>
              <a href='/about'>About</a>
            </nav>
            <div/>
          </div>
        </header>
        <MakeswiftProvider previewMode={(await draftMode()).isEnabled}>
          {children}
        </MakeswiftProvider>
        <footer>
          <div className='p-4 bg-gray-200 text-gray-800'>
            <p>© 2021 Your Company</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
